# Generated by Django 2.1.7 on 2019-03-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
